import Header from '@/components/header/Header'
import './globals.css'
import { Montserrat } from 'next/font/google'
import Footer from '@/components/footer/Footer'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'State',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <div className='container'>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
